apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-web-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yzimm/yaki-devops-lab
    targetRevision: staging
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
